baseurl:
timezone: Europe/Istanbul
destination: _build
exclude: ['README.md', '.gitignore', '.gitkeep' ,'bower_components', 'node_modules', 'rocket-engine', 'bower.json', 'package.json', 'Gruntfile.js', 'assets/styles/styles.css.map', 'assets/scripts/app.js.map']
include: [.htaccess]
markdown: redcarpet